package entity;
// Generated 25/04/2014 10:50:16 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbDetalleFactura generated by hbm2java
 */
public class TbDetalleFactura  implements java.io.Serializable {


     private int dfCod;
     private String dfDescripcion;
     private Integer dfPrecioUnitario;
     private Integer dfExentas;
     private Integer dfCincoPorciento;
     private Integer dfDiezPorciento;
     private String dfUserInsert;
     private String dfUserUpdate;
     private Date dfFechaInsert;
     private Date dfFechaUpdate;
     private Set tbFacturaXDetalleFacturas = new HashSet(0);

    public TbDetalleFactura() {
    }

	
    public TbDetalleFactura(int dfCod, String dfUserInsert, String dfUserUpdate, Date dfFechaInsert, Date dfFechaUpdate) {
        this.dfCod = dfCod;
        this.dfUserInsert = dfUserInsert;
        this.dfUserUpdate = dfUserUpdate;
        this.dfFechaInsert = dfFechaInsert;
        this.dfFechaUpdate = dfFechaUpdate;
    }
    public TbDetalleFactura(int dfCod, String dfDescripcion, Integer dfPrecioUnitario, Integer dfExentas, Integer dfCincoPorciento, Integer dfDiezPorciento, String dfUserInsert, String dfUserUpdate, Date dfFechaInsert, Date dfFechaUpdate, Set tbFacturaXDetalleFacturas) {
       this.dfCod = dfCod;
       this.dfDescripcion = dfDescripcion;
       this.dfPrecioUnitario = dfPrecioUnitario;
       this.dfExentas = dfExentas;
       this.dfCincoPorciento = dfCincoPorciento;
       this.dfDiezPorciento = dfDiezPorciento;
       this.dfUserInsert = dfUserInsert;
       this.dfUserUpdate = dfUserUpdate;
       this.dfFechaInsert = dfFechaInsert;
       this.dfFechaUpdate = dfFechaUpdate;
       this.tbFacturaXDetalleFacturas = tbFacturaXDetalleFacturas;
    }
   
    public int getDfCod() {
        return this.dfCod;
    }
    
    public void setDfCod(int dfCod) {
        this.dfCod = dfCod;
    }
    public String getDfDescripcion() {
        return this.dfDescripcion;
    }
    
    public void setDfDescripcion(String dfDescripcion) {
        this.dfDescripcion = dfDescripcion;
    }
    public Integer getDfPrecioUnitario() {
        return this.dfPrecioUnitario;
    }
    
    public void setDfPrecioUnitario(Integer dfPrecioUnitario) {
        this.dfPrecioUnitario = dfPrecioUnitario;
    }
    public Integer getDfExentas() {
        return this.dfExentas;
    }
    
    public void setDfExentas(Integer dfExentas) {
        this.dfExentas = dfExentas;
    }
    public Integer getDfCincoPorciento() {
        return this.dfCincoPorciento;
    }
    
    public void setDfCincoPorciento(Integer dfCincoPorciento) {
        this.dfCincoPorciento = dfCincoPorciento;
    }
    public Integer getDfDiezPorciento() {
        return this.dfDiezPorciento;
    }
    
    public void setDfDiezPorciento(Integer dfDiezPorciento) {
        this.dfDiezPorciento = dfDiezPorciento;
    }
    public String getDfUserInsert() {
        return this.dfUserInsert;
    }
    
    public void setDfUserInsert(String dfUserInsert) {
        this.dfUserInsert = dfUserInsert;
    }
    public String getDfUserUpdate() {
        return this.dfUserUpdate;
    }
    
    public void setDfUserUpdate(String dfUserUpdate) {
        this.dfUserUpdate = dfUserUpdate;
    }
    public Date getDfFechaInsert() {
        return this.dfFechaInsert;
    }
    
    public void setDfFechaInsert(Date dfFechaInsert) {
        this.dfFechaInsert = dfFechaInsert;
    }
    public Date getDfFechaUpdate() {
        return this.dfFechaUpdate;
    }
    
    public void setDfFechaUpdate(Date dfFechaUpdate) {
        this.dfFechaUpdate = dfFechaUpdate;
    }
    public Set getTbFacturaXDetalleFacturas() {
        return this.tbFacturaXDetalleFacturas;
    }
    
    public void setTbFacturaXDetalleFacturas(Set tbFacturaXDetalleFacturas) {
        this.tbFacturaXDetalleFacturas = tbFacturaXDetalleFacturas;
    }




}


