package entity;
// Generated 06/05/2014 10:35:16 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbFactura generated by hbm2java
 */
public class TbFactura  implements java.io.Serializable {


     private int facCod;
     private TbCliente tbCliente;
     private String facTipo;
     private Integer facNro;
     private Date facFechaEmision;
     private double facTotal;
     private boolean facEstado;
     private String facTimbrado;
     private String facSecuencia;
     private String facUserInsert;
     private String facUserUpdate;
     private Date facFechaInsert;
     private Date facFechaUpdate;
     private Set tbFacturaXDetalleFacturas = new HashSet(0);
     private Set tbPagos = new HashSet(0);
     private Set tbFacturaXContratos = new HashSet(0);

    public TbFactura() {
    }

	
    public TbFactura(int facCod, TbCliente tbCliente, String facTipo, Date facFechaEmision, double facTotal, boolean facEstado, String facUserInsert, String facUserUpdate, Date facFechaInsert, Date facFechaUpdate) {
        this.facCod = facCod;
        this.tbCliente = tbCliente;
        this.facTipo = facTipo;
        this.facFechaEmision = facFechaEmision;
        this.facTotal = facTotal;
        this.facEstado = facEstado;
        this.facUserInsert = facUserInsert;
        this.facUserUpdate = facUserUpdate;
        this.facFechaInsert = facFechaInsert;
        this.facFechaUpdate = facFechaUpdate;
    }
    public TbFactura(int facCod, TbCliente tbCliente, String facTipo, Integer facNro, Date facFechaEmision, double facTotal, boolean facEstado, String facTimbrado, String facSecuencia, String facUserInsert, String facUserUpdate, Date facFechaInsert, Date facFechaUpdate, Set tbFacturaXDetalleFacturas, Set tbPagos, Set tbFacturaXContratos) {
       this.facCod = facCod;
       this.tbCliente = tbCliente;
       this.facTipo = facTipo;
       this.facNro = facNro;
       this.facFechaEmision = facFechaEmision;
       this.facTotal = facTotal;
       this.facEstado = facEstado;
       this.facTimbrado = facTimbrado;
       this.facSecuencia = facSecuencia;
       this.facUserInsert = facUserInsert;
       this.facUserUpdate = facUserUpdate;
       this.facFechaInsert = facFechaInsert;
       this.facFechaUpdate = facFechaUpdate;
       this.tbFacturaXDetalleFacturas = tbFacturaXDetalleFacturas;
       this.tbPagos = tbPagos;
       this.tbFacturaXContratos = tbFacturaXContratos;
    }
   
    public int getFacCod() {
        return this.facCod;
    }
    
    public void setFacCod(int facCod) {
        this.facCod = facCod;
    }
    public TbCliente getTbCliente() {
        return this.tbCliente;
    }
    
    public void setTbCliente(TbCliente tbCliente) {
        this.tbCliente = tbCliente;
    }
    public String getFacTipo() {
        return this.facTipo;
    }
    
    public void setFacTipo(String facTipo) {
        this.facTipo = facTipo;
    }
    public Integer getFacNro() {
        return this.facNro;
    }
    
    public void setFacNro(Integer facNro) {
        this.facNro = facNro;
    }
    public Date getFacFechaEmision() {
        return this.facFechaEmision;
    }
    
    public void setFacFechaEmision(Date facFechaEmision) {
        this.facFechaEmision = facFechaEmision;
    }
    public double getFacTotal() {
        return this.facTotal;
    }
    
    public void setFacTotal(double facTotal) {
        this.facTotal = facTotal;
    }
    public boolean isFacEstado() {
        return this.facEstado;
    }
    
    public void setFacEstado(boolean facEstado) {
        this.facEstado = facEstado;
    }
    public String getFacTimbrado() {
        return this.facTimbrado;
    }
    
    public void setFacTimbrado(String facTimbrado) {
        this.facTimbrado = facTimbrado;
    }
    public String getFacSecuencia() {
        return this.facSecuencia;
    }
    
    public void setFacSecuencia(String facSecuencia) {
        this.facSecuencia = facSecuencia;
    }
    public String getFacUserInsert() {
        return this.facUserInsert;
    }
    
    public void setFacUserInsert(String facUserInsert) {
        this.facUserInsert = facUserInsert;
    }
    public String getFacUserUpdate() {
        return this.facUserUpdate;
    }
    
    public void setFacUserUpdate(String facUserUpdate) {
        this.facUserUpdate = facUserUpdate;
    }
    public Date getFacFechaInsert() {
        return this.facFechaInsert;
    }
    
    public void setFacFechaInsert(Date facFechaInsert) {
        this.facFechaInsert = facFechaInsert;
    }
    public Date getFacFechaUpdate() {
        return this.facFechaUpdate;
    }
    
    public void setFacFechaUpdate(Date facFechaUpdate) {
        this.facFechaUpdate = facFechaUpdate;
    }
    public Set getTbFacturaXDetalleFacturas() {
        return this.tbFacturaXDetalleFacturas;
    }
    
    public void setTbFacturaXDetalleFacturas(Set tbFacturaXDetalleFacturas) {
        this.tbFacturaXDetalleFacturas = tbFacturaXDetalleFacturas;
    }
    public Set getTbPagos() {
        return this.tbPagos;
    }
    
    public void setTbPagos(Set tbPagos) {
        this.tbPagos = tbPagos;
    }
    public Set getTbFacturaXContratos() {
        return this.tbFacturaXContratos;
    }
    
    public void setTbFacturaXContratos(Set tbFacturaXContratos) {
        this.tbFacturaXContratos = tbFacturaXContratos;
    }




}


