package entity;
// Generated 12/05/2014 11:58:21 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TbGasto generated by hbm2java
 */
public class TbGasto  implements java.io.Serializable {


     private int gaCod;
     private String gaConcepto;
     private Double gaMonto;
     private Date gaFecha;
     private String gaResponsable;
     private String gaUserInsert;
     private String gaUserUpdate;
     private Date gaFechaInsert;
     private Date gaFechaUpdate;

    public TbGasto() {
    }

	
    public TbGasto(int gaCod, String gaConcepto, Date gaFecha, String gaResponsable, String gaUserInsert, String gaUserUpdate, Date gaFechaInsert, Date gaFechaUpdate) {
        this.gaCod = gaCod;
        this.gaConcepto = gaConcepto;
        this.gaFecha = gaFecha;
        this.gaResponsable = gaResponsable;
        this.gaUserInsert = gaUserInsert;
        this.gaUserUpdate = gaUserUpdate;
        this.gaFechaInsert = gaFechaInsert;
        this.gaFechaUpdate = gaFechaUpdate;
    }
    public TbGasto(int gaCod, String gaConcepto, Double gaMonto, Date gaFecha, String gaResponsable, String gaUserInsert, String gaUserUpdate, Date gaFechaInsert, Date gaFechaUpdate) {
       this.gaCod = gaCod;
       this.gaConcepto = gaConcepto;
       this.gaMonto = gaMonto;
       this.gaFecha = gaFecha;
       this.gaResponsable = gaResponsable;
       this.gaUserInsert = gaUserInsert;
       this.gaUserUpdate = gaUserUpdate;
       this.gaFechaInsert = gaFechaInsert;
       this.gaFechaUpdate = gaFechaUpdate;
    }
   
    public int getGaCod() {
        return this.gaCod;
    }
    
    public void setGaCod(int gaCod) {
        this.gaCod = gaCod;
    }
    public String getGaConcepto() {
        return this.gaConcepto;
    }
    
    public void setGaConcepto(String gaConcepto) {
        this.gaConcepto = gaConcepto;
    }
    public Double getGaMonto() {
        return this.gaMonto;
    }
    
    public void setGaMonto(Double gaMonto) {
        this.gaMonto = gaMonto;
    }
    public Date getGaFecha() {
        return this.gaFecha;
    }
    
    public void setGaFecha(Date gaFecha) {
        this.gaFecha = gaFecha;
    }
    public String getGaResponsable() {
        return this.gaResponsable;
    }
    
    public void setGaResponsable(String gaResponsable) {
        this.gaResponsable = gaResponsable;
    }
    public String getGaUserInsert() {
        return this.gaUserInsert;
    }
    
    public void setGaUserInsert(String gaUserInsert) {
        this.gaUserInsert = gaUserInsert;
    }
    public String getGaUserUpdate() {
        return this.gaUserUpdate;
    }
    
    public void setGaUserUpdate(String gaUserUpdate) {
        this.gaUserUpdate = gaUserUpdate;
    }
    public Date getGaFechaInsert() {
        return this.gaFechaInsert;
    }
    
    public void setGaFechaInsert(Date gaFechaInsert) {
        this.gaFechaInsert = gaFechaInsert;
    }
    public Date getGaFechaUpdate() {
        return this.gaFechaUpdate;
    }
    
    public void setGaFechaUpdate(Date gaFechaUpdate) {
        this.gaFechaUpdate = gaFechaUpdate;
    }




}


