package entity;
// Generated 25/04/2014 01:54:57 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TbRolesXUsuario generated by hbm2java
 */
public class TbRolesXUsuario  implements java.io.Serializable {


     private int rouCod;
     private TbRoles tbRoles;
     private TbUsuario tbUsuario;
     private String rouUserInsert;
     private String rouUserUpdate;
     private Date rouFechaInsert;
     private Date rouFechaUpdate;

    public TbRolesXUsuario() {
    }

    public TbRolesXUsuario(int rouCod, TbRoles tbRoles, TbUsuario tbUsuario, String rouUserInsert, String rouUserUpdate, Date rouFechaInsert, Date rouFechaUpdate) {
       this.rouCod = rouCod;
       this.tbRoles = tbRoles;
       this.tbUsuario = tbUsuario;
       this.rouUserInsert = rouUserInsert;
       this.rouUserUpdate = rouUserUpdate;
       this.rouFechaInsert = rouFechaInsert;
       this.rouFechaUpdate = rouFechaUpdate;
    }
   
    public int getRouCod() {
        return this.rouCod;
    }
    
    public void setRouCod(int rouCod) {
        this.rouCod = rouCod;
    }
    public TbRoles getTbRoles() {
        return this.tbRoles;
    }
    
    public void setTbRoles(TbRoles tbRoles) {
        this.tbRoles = tbRoles;
    }
    public TbUsuario getTbUsuario() {
        return this.tbUsuario;
    }
    
    public void setTbUsuario(TbUsuario tbUsuario) {
        this.tbUsuario = tbUsuario;
    }
    public String getRouUserInsert() {
        return this.rouUserInsert;
    }
    
    public void setRouUserInsert(String rouUserInsert) {
        this.rouUserInsert = rouUserInsert;
    }
    public String getRouUserUpdate() {
        return this.rouUserUpdate;
    }
    
    public void setRouUserUpdate(String rouUserUpdate) {
        this.rouUserUpdate = rouUserUpdate;
    }
    public Date getRouFechaInsert() {
        return this.rouFechaInsert;
    }
    
    public void setRouFechaInsert(Date rouFechaInsert) {
        this.rouFechaInsert = rouFechaInsert;
    }
    public Date getRouFechaUpdate() {
        return this.rouFechaUpdate;
    }
    
    public void setRouFechaUpdate(Date rouFechaUpdate) {
        this.rouFechaUpdate = rouFechaUpdate;
    }




}


