package entity;
// Generated 29/04/2014 10:12:33 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbRoles generated by hbm2java
 */
public class TbRoles  implements java.io.Serializable {


     private int rolCod;
     private String rolNombre;
     private String rolUserInsert;
     private String rolUserUpdate;
     private Date rolFechaInsert;
     private Date rolFechaUpdate;
     private Set tbRolesXPermisos = new HashSet(0);
     private Set tbRolesXUsuarios = new HashSet(0);

    public TbRoles() {
    }

	
    public TbRoles(int rolCod, String rolUserInsert, String rolUserUpdate, Date rolFechaInsert, Date rolFechaUpdate) {
        this.rolCod = rolCod;
        this.rolUserInsert = rolUserInsert;
        this.rolUserUpdate = rolUserUpdate;
        this.rolFechaInsert = rolFechaInsert;
        this.rolFechaUpdate = rolFechaUpdate;
    }
    public TbRoles(int rolCod, String rolNombre, String rolUserInsert, String rolUserUpdate, Date rolFechaInsert, Date rolFechaUpdate, Set tbRolesXPermisos, Set tbRolesXUsuarios) {
       this.rolCod = rolCod;
       this.rolNombre = rolNombre;
       this.rolUserInsert = rolUserInsert;
       this.rolUserUpdate = rolUserUpdate;
       this.rolFechaInsert = rolFechaInsert;
       this.rolFechaUpdate = rolFechaUpdate;
       this.tbRolesXPermisos = tbRolesXPermisos;
       this.tbRolesXUsuarios = tbRolesXUsuarios;
    }
   
    public int getRolCod() {
        return this.rolCod;
    }
    
    public void setRolCod(int rolCod) {
        this.rolCod = rolCod;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public String getRolUserInsert() {
        return this.rolUserInsert;
    }
    
    public void setRolUserInsert(String rolUserInsert) {
        this.rolUserInsert = rolUserInsert;
    }
    public String getRolUserUpdate() {
        return this.rolUserUpdate;
    }
    
    public void setRolUserUpdate(String rolUserUpdate) {
        this.rolUserUpdate = rolUserUpdate;
    }
    public Date getRolFechaInsert() {
        return this.rolFechaInsert;
    }
    
    public void setRolFechaInsert(Date rolFechaInsert) {
        this.rolFechaInsert = rolFechaInsert;
    }
    public Date getRolFechaUpdate() {
        return this.rolFechaUpdate;
    }
    
    public void setRolFechaUpdate(Date rolFechaUpdate) {
        this.rolFechaUpdate = rolFechaUpdate;
    }
    public Set getTbRolesXPermisos() {
        return this.tbRolesXPermisos;
    }
    
    public void setTbRolesXPermisos(Set tbRolesXPermisos) {
        this.tbRolesXPermisos = tbRolesXPermisos;
    }
    public Set getTbRolesXUsuarios() {
        return this.tbRolesXUsuarios;
    }
    
    public void setTbRolesXUsuarios(Set tbRolesXUsuarios) {
        this.tbRolesXUsuarios = tbRolesXUsuarios;
    }




}


