package entity;
// Generated 29/04/2014 10:12:33 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbTimbrado generated by hbm2java
 */
public class TbTimbrado  implements java.io.Serializable {


     private int timCod;
     private boolean timEstado;
     private String timTipo;
     private String timNro;
     private String timSecuencia;
     private Date timInicioVigencia;
     private Date timFinVigencia;
     private String timRuc;
     private String timUserInsert;
     private String timUserUpdate;
     private Date timFechaInsert;
     private Date timFechaUpdate;
     private Set tbFacturas = new HashSet(0);

    public TbTimbrado() {
    }

	
    public TbTimbrado(int timCod, boolean timEstado, String timTipo, String timNro, Date timInicioVigencia, Date timFinVigencia, String timRuc, String timUserInsert, String timUserUpdate, Date timFechaInsert, Date timFechaUpdate) {
        this.timCod = timCod;
        this.timEstado = timEstado;
        this.timTipo = timTipo;
        this.timNro = timNro;
        this.timInicioVigencia = timInicioVigencia;
        this.timFinVigencia = timFinVigencia;
        this.timRuc = timRuc;
        this.timUserInsert = timUserInsert;
        this.timUserUpdate = timUserUpdate;
        this.timFechaInsert = timFechaInsert;
        this.timFechaUpdate = timFechaUpdate;
    }
    public TbTimbrado(int timCod, boolean timEstado, String timTipo, String timNro, String timSecuencia, Date timInicioVigencia, Date timFinVigencia, String timRuc, String timUserInsert, String timUserUpdate, Date timFechaInsert, Date timFechaUpdate, Set tbFacturas) {
       this.timCod = timCod;
       this.timEstado = timEstado;
       this.timTipo = timTipo;
       this.timNro = timNro;
       this.timSecuencia = timSecuencia;
       this.timInicioVigencia = timInicioVigencia;
       this.timFinVigencia = timFinVigencia;
       this.timRuc = timRuc;
       this.timUserInsert = timUserInsert;
       this.timUserUpdate = timUserUpdate;
       this.timFechaInsert = timFechaInsert;
       this.timFechaUpdate = timFechaUpdate;
       this.tbFacturas = tbFacturas;
    }
   
    public int getTimCod() {
        return this.timCod;
    }
    
    public void setTimCod(int timCod) {
        this.timCod = timCod;
    }
    public boolean isTimEstado() {
        return this.timEstado;
    }
    
    public void setTimEstado(boolean timEstado) {
        this.timEstado = timEstado;
    }
    public String getTimTipo() {
        return this.timTipo;
    }
    
    public void setTimTipo(String timTipo) {
        this.timTipo = timTipo;
    }
    public String getTimNro() {
        return this.timNro;
    }
    
    public void setTimNro(String timNro) {
        this.timNro = timNro;
    }
    public String getTimSecuencia() {
        return this.timSecuencia;
    }
    
    public void setTimSecuencia(String timSecuencia) {
        this.timSecuencia = timSecuencia;
    }
    public Date getTimInicioVigencia() {
        return this.timInicioVigencia;
    }
    
    public void setTimInicioVigencia(Date timInicioVigencia) {
        this.timInicioVigencia = timInicioVigencia;
    }
    public Date getTimFinVigencia() {
        return this.timFinVigencia;
    }
    
    public void setTimFinVigencia(Date timFinVigencia) {
        this.timFinVigencia = timFinVigencia;
    }
    public String getTimRuc() {
        return this.timRuc;
    }
    
    public void setTimRuc(String timRuc) {
        this.timRuc = timRuc;
    }
    public String getTimUserInsert() {
        return this.timUserInsert;
    }
    
    public void setTimUserInsert(String timUserInsert) {
        this.timUserInsert = timUserInsert;
    }
    public String getTimUserUpdate() {
        return this.timUserUpdate;
    }
    
    public void setTimUserUpdate(String timUserUpdate) {
        this.timUserUpdate = timUserUpdate;
    }
    public Date getTimFechaInsert() {
        return this.timFechaInsert;
    }
    
    public void setTimFechaInsert(Date timFechaInsert) {
        this.timFechaInsert = timFechaInsert;
    }
    public Date getTimFechaUpdate() {
        return this.timFechaUpdate;
    }
    
    public void setTimFechaUpdate(Date timFechaUpdate) {
        this.timFechaUpdate = timFechaUpdate;
    }
    public Set getTbFacturas() {
        return this.tbFacturas;
    }
    
    public void setTbFacturas(Set tbFacturas) {
        this.tbFacturas = tbFacturas;
    }




}


