package entity;
// Generated 09/05/2014 01:09:38 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * TbTimbrado generated by hbm2java
 */
public class TbTimbrado  implements java.io.Serializable {


     private int timCod;
     private boolean timEstado;
     private String timTipo;
     private String timNro;
     private Date timInicioVigencia;
     private Date timFinVigencia;
     private String timRuc;
     private int timSecuencia;
     private String timSetuno;
     private String timSetdos;
     private String timUserInsert;
     private String timUserUpdate;
     private Date timFechaInsert;
     private Date timFechaUpdate;

    public TbTimbrado() {
    }

    public TbTimbrado(int timCod, boolean timEstado, String timTipo, String timNro, Date timInicioVigencia, Date timFinVigencia, String timRuc, int timSecuencia, String timSetuno, String timSetdos, String timUserInsert, String timUserUpdate, Date timFechaInsert, Date timFechaUpdate) {
       this.timCod = timCod;
       this.timEstado = timEstado;
       this.timTipo = timTipo;
       this.timNro = timNro;
       this.timInicioVigencia = timInicioVigencia;
       this.timFinVigencia = timFinVigencia;
       this.timRuc = timRuc;
       this.timSecuencia = timSecuencia;
       this.timSetuno = timSetuno;
       this.timSetdos = timSetdos;
       this.timUserInsert = timUserInsert;
       this.timUserUpdate = timUserUpdate;
       this.timFechaInsert = timFechaInsert;
       this.timFechaUpdate = timFechaUpdate;
    }
   
    public int getTimCod() {
        return this.timCod;
    }
    
    public void setTimCod(int timCod) {
        this.timCod = timCod;
    }
    public boolean isTimEstado() {
        return this.timEstado;
    }
    
    public void setTimEstado(boolean timEstado) {
        this.timEstado = timEstado;
    }
    public String getTimTipo() {
        return this.timTipo;
    }
    
    public void setTimTipo(String timTipo) {
        this.timTipo = timTipo;
    }
    public String getTimNro() {
        return this.timNro;
    }
    
    public void setTimNro(String timNro) {
        this.timNro = timNro;
    }
    public Date getTimInicioVigencia() {
        return this.timInicioVigencia;
    }
    
    public void setTimInicioVigencia(Date timInicioVigencia) {
        this.timInicioVigencia = timInicioVigencia;
    }
    public Date getTimFinVigencia() {
        return this.timFinVigencia;
    }
    
    public void setTimFinVigencia(Date timFinVigencia) {
        this.timFinVigencia = timFinVigencia;
    }
    public String getTimRuc() {
        return this.timRuc;
    }
    
    public void setTimRuc(String timRuc) {
        this.timRuc = timRuc;
    }
    public int getTimSecuencia() {
        return this.timSecuencia;
    }
    
    public void setTimSecuencia(int timSecuencia) {
        this.timSecuencia = timSecuencia;
    }
    public String getTimSetuno() {
        return this.timSetuno;
    }
    
    public void setTimSetuno(String timSetuno) {
        this.timSetuno = timSetuno;
    }
    public String getTimSetdos() {
        return this.timSetdos;
    }
    
    public void setTimSetdos(String timSetdos) {
        this.timSetdos = timSetdos;
    }
    public String getTimUserInsert() {
        return this.timUserInsert;
    }
    
    public void setTimUserInsert(String timUserInsert) {
        this.timUserInsert = timUserInsert;
    }
    public String getTimUserUpdate() {
        return this.timUserUpdate;
    }
    
    public void setTimUserUpdate(String timUserUpdate) {
        this.timUserUpdate = timUserUpdate;
    }
    public Date getTimFechaInsert() {
        return this.timFechaInsert;
    }
    
    public void setTimFechaInsert(Date timFechaInsert) {
        this.timFechaInsert = timFechaInsert;
    }
    public Date getTimFechaUpdate() {
        return this.timFechaUpdate;
    }
    
    public void setTimFechaUpdate(Date timFechaUpdate) {
        this.timFechaUpdate = timFechaUpdate;
    }




}


