package entity;
// Generated 25/04/2014 01:54:57 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbTipoServicio generated by hbm2java
 */
public class TbTipoServicio  implements java.io.Serializable {


     private int tsCod;
     private String tsDescripcion;
     private String tsUserInsert;
     private String tsUserUpdate;
     private Date tsFechaInsert;
     private Date tsFechaUpdate;
     private Set tbServicios = new HashSet(0);

    public TbTipoServicio() {
    }

	
    public TbTipoServicio(int tsCod, String tsUserInsert, String tsUserUpdate, Date tsFechaInsert, Date tsFechaUpdate) {
        this.tsCod = tsCod;
        this.tsUserInsert = tsUserInsert;
        this.tsUserUpdate = tsUserUpdate;
        this.tsFechaInsert = tsFechaInsert;
        this.tsFechaUpdate = tsFechaUpdate;
    }
    public TbTipoServicio(int tsCod, String tsDescripcion, String tsUserInsert, String tsUserUpdate, Date tsFechaInsert, Date tsFechaUpdate, Set tbServicios) {
       this.tsCod = tsCod;
       this.tsDescripcion = tsDescripcion;
       this.tsUserInsert = tsUserInsert;
       this.tsUserUpdate = tsUserUpdate;
       this.tsFechaInsert = tsFechaInsert;
       this.tsFechaUpdate = tsFechaUpdate;
       this.tbServicios = tbServicios;
    }
   
    public int getTsCod() {
        return this.tsCod;
    }
    
    public void setTsCod(int tsCod) {
        this.tsCod = tsCod;
    }
    public String getTsDescripcion() {
        return this.tsDescripcion;
    }
    
    public void setTsDescripcion(String tsDescripcion) {
        this.tsDescripcion = tsDescripcion;
    }
    public String getTsUserInsert() {
        return this.tsUserInsert;
    }
    
    public void setTsUserInsert(String tsUserInsert) {
        this.tsUserInsert = tsUserInsert;
    }
    public String getTsUserUpdate() {
        return this.tsUserUpdate;
    }
    
    public void setTsUserUpdate(String tsUserUpdate) {
        this.tsUserUpdate = tsUserUpdate;
    }
    public Date getTsFechaInsert() {
        return this.tsFechaInsert;
    }
    
    public void setTsFechaInsert(Date tsFechaInsert) {
        this.tsFechaInsert = tsFechaInsert;
    }
    public Date getTsFechaUpdate() {
        return this.tsFechaUpdate;
    }
    
    public void setTsFechaUpdate(Date tsFechaUpdate) {
        this.tsFechaUpdate = tsFechaUpdate;
    }
    public Set getTbServicios() {
        return this.tbServicios;
    }
    
    public void setTbServicios(Set tbServicios) {
        this.tbServicios = tbServicios;
    }




}


